const DISCOVER_MOVIES = "DISCOVER_MOVIES";
const GENRES_MOVIES = "GENRES_MOVIES";
const MOVIES_BY_GENRE = "MOVIES_BY_GENRE";
const SEARCH_MOVIE = "SEARCH_MOVIE";
const ADD_USER = "ADD_USER";


export {DISCOVER_MOVIES, GENRES_MOVIES, MOVIES_BY_GENRE, SEARCH_MOVIE, ADD_USER};